version: "3.1"
services:
  react-first:
    container_name: react-first
    build:
      context: ./docker
      dockerfile: Dockerfile
    image:  react-first:v1
    ports:
      - "80:80"
    volumes:
      - ./build/public:/app/public
